name: todo
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.1.0
  curved_navigation_bar: ^1.0.6
  animations: ^2.0.11
  tab_indicator_styler: ^2.0.0
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  uuid: ^4.5.1
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - 'assets/home.png'
    - 'assets/add_todo.png'
    - 'assets/finance.jpg'
    - 'assets/Career.jpg'
    - 'assets/Health.jpg'
    - 'assets/Leisure.jpg'
    - 'assets/Office.jpg'
    - 'assets/Home.jpg'
    - 'assets/Personal.jpg'
    - 'assets/Self_Development.jpg'
    - 'assets/Fun.jpg'
  
   

